spring:
  datasource:
    url: jdbc:mysql://localhost:3306/capstone
    username: root                     # MySQL username
    password: RrVvL@2545                     # MySQL password
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL JDBC driver class

  jpa:
    hibernate:
      ddl-auto: update  # Automatically update the database schema based on entities

    # Optionally configure connection pool settings
    # Minimum number of idle connections in the pool

server:
  port: 9099